# Generated by Django 4.2.29 on 2026-04-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=50, unique=True)),
                ("device_name", models.CharField(max_length=100)),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("gas", "가스"),
                            ("power", "전력"),
                            ("temperature", "온도"),
                            ("motion", "동작"),
                        ],
                        default="gas",
                        max_length=20,
                    ),
                ),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("caution", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("last_value", models.FloatField(blank=True, null=True)),
                (
                    "last_value_unit",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeoFence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("danger", "위험"),
                            ("caution", "주의"),
                            ("restricted", "출입금지"),
                        ],
                        default="danger",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "보통"),
                            ("high", "높음"),
                            ("critical", "심각"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("polygon", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_type",
                    models.CharField(
                        choices=[
                            ("geofence_enter", "위험구역 진입"),
                            ("sensor_caution", "센서 주의"),
                            ("sensor_danger", "센서 위험"),
                            ("combined", "복합 위험"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "alarm_level",
                    models.CharField(
                        choices=[
                            ("info", "정보"),
                            ("caution", "주의"),
                            ("danger", "위험"),
                            ("critical", "심각"),
                        ],
                        default="caution",
                        max_length=20,
                    ),
                ),
                ("worker_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "worker_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("worker_x", models.FloatField(blank=True, null=True)),
                ("worker_y", models.FloatField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "sensor_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "geofence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarms",
                        to="monitor.geofence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
