# Generated by Django 4.2.29 on 2026-04-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자 목록"},
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="연락처"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="소속 부서"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("operator", "운영자"), ("admin", "관리자")],
                default="operator",
                max_length=20,
                verbose_name="역할",
            ),
        ),
    ]
