# Generated by Django 5.2.13 on 2026-04-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=50, unique=True)),
                ("device_name", models.CharField(max_length=100)),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("gas", "가스"),
                            ("power", "전력"),
                            ("temperature", "온도"),
                            ("motion", "동작"),
                        ],
                        default="gas",
                        max_length=20,
                    ),
                ),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("caution", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("last_value", models.FloatField(blank=True, null=True)),
                (
                    "last_value_unit",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeoFence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("danger", "위험"),
                            ("caution", "주의"),
                            ("restricted", "출입금지"),
                        ],
                        default="danger",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "보통"),
                            ("high", "높음"),
                            ("critical", "심각"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("polygon", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
