# Generated by Django 4.2.29 on 2026-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("CO", models.FloatField()),
                ("H2S", models.FloatField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("risk_score", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
